#!/bin/bash

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Keep computer awake
pmset noidle &
PMSETPID=$!

pushd ./scripts
    echo "Install homebrew and its packages"
    . brew

    echo "Install ruby versions"
    . rubies

    echo "Install node packages"
    . npm

    echo "Check OSX apps"
    . check

    echo "Set system defaults"
    . osx

    echo "Symlink dotfiles"
    . symlink
popd

printf "\n\n---\n"
read -p "Everything's done, reboot now? (y/n) " -n 1
echo

# You can go to sleep now
kill $PMSETPID

if [[ $REPLY =~ ^[Yy]$ ]]; then
  sudo reboot
fi

