#!/bin/bash

# Table of content:
# 1. Symlink files
# 2. Install system packages
# 3. Install NPM packages
# 4. Install Ruby versions
# 5. Install OSX apps
# 6. Install Metasploit
# 7. Configure OSX

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.osx` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

# Keep computer awake
pmset noidle &
PMSETPID=$!

# Do the thing
. scripts/1-symlink
. scripts/2-system-packages
. scripts/3-npm-packages
. scripts/4-rubies
. scripts/5-osx-apps
. scripts/6-metasploit
. scripts/7-osx-preferences
. scripts/8-osx-check-apps

printf "\n\n---\n"
read -p "Everything's done, reboot now? (y/n) " -n 1
echo

# You can go to sleep now
kill $PMSETPID

if [[ $REPLY =~ ^[Yy]$ ]]; then
  sudo reboot
fi

